-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: fix-encoding-pragma
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: detect-private-key
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.1
    hooks:
    -   id: reorder-python-imports
