-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: detect-private-key
