#!/bin/bash
set -euf -o pipefail

if [ ! -f "$1" ]; then
    echo "not a file: "$1""
    exit 1
fi

case $1 in
    *.tar.gz)  tar zxvf $1;;
    *.tar.bz2) tar jxvf $1;;
    *.bz2)     bunzip2 $1;;
    *.rar)     unrar x $1;;
    *.gz)      gzip -d $1;;
    *.tar)     tar xvf $1;;
    *.zip)     unzip $1;;
    *)         echo "unrecognized extension";;
esac
